include ../common.mk

examples: \
	example_auto_cpp14 example_auto_cpp11 \
	example_const_cpp14 example_const_cpp11 \
	example_exception_cpp14 example_exception_cpp11 \
	example_lambda_cpp14 example_lambda_cpp11 \
	example_smart_ptr_cpp14 example_smart_ptr_cpp11
