include ../common.mk

example_thread_cpp14_ld_flags=-lpthread
example_thread_cpp11_ld_flags=-lpthread

examples: \
	example_algo_cpp14 example_algo_cpp11 \
	example_container_cpp14 example_container_cpp11 \
	example_string_cpp14 example_string_cpp11 \
	example_thread_cpp14 example_thread_cpp11
