# Copyright (c) 2020 by Chrono

set -o vi
alias ll='ls -l'
alias l='ls -lh'
alias vi='vim'

function set-title() {
    if [[ -z "$ORIG" ]]; then
        ORIG=$PS1
    fi
    TITLE="\[\e]2;$*\a\]"
    PS1=${ORIG}${TITLE}
}
